server:
  port: 8080

spring:
  application:
    name: finance
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=finances;encrypt=true;trustServerCertificate=true;
    username: tbrfinancas
    password: 1234567
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    trustServerCertificate: true
  flyway:
    enabled: true
    locations: classpath:db/migration/prod

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}