CREATE TABLE MODALIDADE_PAGAMENTO (
ID UNIQUEIDENTIFIER PRIMARY KEY,
NOME_MODALIDADE VARCHAR(50),
TIPO_MODALIDADE VARCHAR(10),
OWNER_ID UNIQUEIDENTIFIER,
CREATED_AT DATETIME,
FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
)